### ISSUE TITLE
qr broken due to data installation

### ISSUE THREAD

**Issue by jvanasco** [hudora/huBarcode#2]
this took me a while to figure out:

the qrcode implementation won't work if installed via the current trunk , because the qrcode_data directory isn't installed along with it.

the qrcode_generate_Data.py script doesn't seem to work either, because it doesn't like the way stuff is laid out

my inelegant fix was to migrate the  qrcode_data that was in trunk into the python egg.

**Comment by mdornseif** [comment]
Ugh. The QR-code tables are an issue since the first implementation. We had two implementations: one of the files in externam datafiles and one where we stuffed the tables in python modules. To be frank: I'm not sure which one we currently use, since we only use datamatrix in production.

**Comment by mdornseif** [comment]
Should be fixed in v0.61

**Comment by jvanasco** [comment]
rad! i'll give it a test over the weekend and if there's an issue maybe i can help fix.
