### ISSUE TITLE
Create a new release tag for current version.

### ISSUE THREAD

**Issue by radicalbiscuit** [hudora/huBarcode#21]
I use this software and our legal page attributes the correct license. I'm writing a dynamic way of getting the licenses for current versions of the packages we use. One of the strategies is pulling the LICENSE file for a given version from release branches on github or whatever hosting provider the project in question is using.

Currently, the latest (and only) release branch tagged on this project is 0.6.2, even though the PyPI package and commit comments indicate that 0.63 is the latest version. A simple version bump tag would be in order.

Also, the versioning convention should be reviewed and sync'd between github and PyPI. I imagine the "current" version is supposed to be 0.6.3 rather than 0.63.

**Comment by mdornseif** [comment]
Fixed in cff1af88ba5156b8a2d6a1e818054ee46c858b73
