### ISSUE TITLE
Re-size datamatrix? 

### ISSUE THREAD

**Issue by genomics-admin** [hudora/huBarcode#25]
Hi,

I can get the data matrix images in a 80x80 pixel format but i'm not able to change the size of this image either increase or decrease the image by , lets say 50%(40x40 pixel) or 150%(120x120 pixel).

i have tried altering the .height and .width parameter but i think they are for bar codes and not for data matrix.

is there a solution for this?

**Comment by mdornseif** [comment]
Probably. If you want to make it configurable you are welcome to submit a pull request. Or just re-scale the Image after creation.
